# Ensure all checks are run to reduce back-and-forth between fixing and checking
fail_fast: false

default_stages: [pre-commit, pre-push]
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test

      # Check Shell
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

      # Check JSON/YAML
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^charts/pr-sandbox-automation/templates/.*\.yaml$
      - id: check-json
      - id: pretty-format-json
        args: [--no-sort-keys]

      # Check files
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

      # Check Git
      - id: forbid-new-submodules
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: no-commit-to-branch
        name: no-commit-to-main
        args: [--branch, main]

  # Check Python Formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.8
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # Check Markdown Formatting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2

  # Check Shell Formatting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  # Check Commit Messages
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: ["--strict", "--config", ".github/.commitlintrc.mjs"]
        additional_dependencies:
          - "@commitlint/config-conventional"
          - commitlint-plugin-function-rules
