secrets:
  pr-sandbox-github-webhook-secret:
    file: dev/secrets/pr-sandbox-github-webhook-secret
  pr-sandbox-github-private-key:
    file: dev/secrets/pr-sandbox-github-private-key
  pr-sandbox-pr-installation-id:
    file: dev/secrets/pr-sandbox-pr-installation-id
  pr-sandbox-cluster-installation-id:
    file: dev/secrets/pr-sandbox-cluster-installation-id
  pr-sandbox-mysql-connection-string:
    file: dev/secrets/pr-sandbox-mysql-connection-string
  pr-sandbox-argocd-webhook-auth:
    file: dev/secrets/pr-sandbox-argocd-webhook-auth


services:
  dev-db:
    container_name: mysql-dev
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pr_sandbox
      MYSQL_USER: pr-sandbox-mysql-user
      MYSQL_PASSWORD: pr-sandbox-mysql-password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  dev-app:
    container_name: pr-sandbox-automation-dev-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - dev/dev.env
    depends_on:
      - dev-db
    secrets:
      - pr-sandbox-github-webhook-secret
      - pr-sandbox-github-private-key
      - pr-sandbox-pr-installation-id
      - pr-sandbox-cluster-installation-id
      - pr-sandbox-mysql-connection-string
      - pr-sandbox-argocd-webhook-auth
    ports:
      - "8900:8900"
    volumes:
      - .:/app

volumes:
  db_data: {}
