"""Initial Migration

Revision ID: 027fd2358fb8
Revises:
Create Date: 2025-12-08 08:48:30.884333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "027fd2358fb8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cancelledrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cancelledrun_run_id"), "cancelledrun", ["run_id"], unique=True
    )
    op.create_table(
        "checkrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("check_run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("head_sha", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sandbox_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("check_suite_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pr_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("build_complete", sa.Boolean(), nullable=False),
        sa.Column(
            "deployment_status",
            sa.Enum(
                "CANCELLED",
                "IN_PROGRESS",
                "COMPLETE",
                "FAILURE",
                "SUCCESS",
                name="checkrunstatus",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkrun_build_complete"), "checkrun", ["build_complete"], unique=False
    )
    op.create_index(
        op.f("ix_checkrun_check_run_id"), "checkrun", ["check_run_id"], unique=True
    )
    op.create_index(
        op.f("ix_checkrun_check_suite_id"), "checkrun", ["check_suite_id"], unique=False
    )
    op.create_index(
        op.f("ix_checkrun_deployment_status"),
        "checkrun",
        ["deployment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkrun_sandbox_name"), "checkrun", ["sandbox_name"], unique=False
    )
    op.create_table(
        "sandboxaudit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_html_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pr_html_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fork_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sandbox_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sandbox_status",
            sa.Enum("CREATED", "UPDATED", "DESTROYED", name="sandboxstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sandboxaudit_repo"), "sandboxaudit", ["repo"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sandboxaudit_repo"), table_name="sandboxaudit")
    op.drop_table("sandboxaudit")
    op.drop_index(op.f("ix_checkrun_sandbox_name"), table_name="checkrun")
    op.drop_index(op.f("ix_checkrun_deployment_status"), table_name="checkrun")
    op.drop_index(op.f("ix_checkrun_check_suite_id"), table_name="checkrun")
    op.drop_index(op.f("ix_checkrun_check_run_id"), table_name="checkrun")
    op.drop_index(op.f("ix_checkrun_build_complete"), table_name="checkrun")
    op.drop_table("checkrun")
    op.drop_index(op.f("ix_cancelledrun_run_id"), table_name="cancelledrun")
    op.drop_table("cancelledrun")
    # ### end Alembic commands ###
