apiVersion: v1
kind: Service
metadata:
  name: {{ include "pr-sandbox-automation.fullname" . }}
  labels:
    {{- include "pr-sandbox-automation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pr-sandbox-automation.selectorLabels" . | nindent 4 }}
