{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pr-sandbox-automation.serviceAccountName" . }}
  labels:
    {{- include "pr-sandbox-automation.labels" . | nindent 4 }}
{{- end }}
